version: '3.8'

services:
  odoo:
    container_name: odoo-container
    image: odoo:latest
    volumes:
      - odoo_data:/var/lib/odoo
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    command: ["odoo", "-d", "odoo", "-i", "base"]
    networks:
      - odoo_network

  db:
    image: postgres:latest
    container_name: odoo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    networks:
      - odoo_network

  nginx:
    image: nginx:latest
    container_name: odoo-proxy
    ports:
      - "8080:80"  # HABIA QUE ACCEDER a Odoo con CORS v√≠a http://localhost:8080 LJNSCDKVJSN MATAME
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - odoo
    networks:
      - odoo_network

volumes:
  odoo_db_data:
  odoo_data:

networks:
  odoo_network:
    driver: bridge